language: java
addons:
  sonarcloud:
    organization: "10sankar"
    token:
      secure: $SONAR_TOKEN

script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
