language: java
addons:
  sonarcloud:
    organization: alefanfi
    token: fae47b803191c687dc98db3ca0237e77537b6059
script:
  - mvn verify -DfailIfNoTests=false sonar:sonar -Dsonar.projectKey=alefanfi_bookkeeper_demo
#addons:
 # sonarcloud:
  #  organization: "10sankar"
   # token: ""
#script:
 # - mvn clean verify sonar:sonar -Pcoverage
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
  #- mvn clean install org.sonarsource.scanner.maven:sonar-maven-plugin:3.7.0.1746:sonar
